### ISSUE TITLE
Duplicate trade flows still a problem for South Africa and other areas NES (maybe also other members of SACU)

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/faoswsTrade#157] opened 2017-09-04 14:12 UTC
Several examples of identical flows being recorded for South Africa and other partner, in both the tool and the working system. This will affect the trade totals. Not sure if it is also a problem for other SACU members.

See screenshots:
INDONESIA
![image](https://user-images.githubusercontent.com/31275016/30029985-b330e4d6-918b-11e7-873f-2702b4c0b590.png)
![image](https://user-images.githubusercontent.com/31275016/30029986-b614b8a8-918b-11e7-81a4-291550643dc5.png)
![image](https://user-images.githubusercontent.com/31275016/30029990-b87e5d7e-918b-11e7-993f-cc9943ce3f4b.png)
THAILAND
![image](https://user-images.githubusercontent.com/31275016/30030005-c331ab36-918b-11e7-84bb-cb7dc7e4b040.png)
![image](https://user-images.githubusercontent.com/31275016/30030013-cb85d870-918b-11e7-8588-4b7633bbf5c5.png)
![image](https://user-images.githubusercontent.com/31275016/30030018-cd3cb30a-918b-11e7-8615-f155904768c8.png)

**Comment by chrmongeau** [comment] 2017-09-04 15:13
The issue with SACU itself was fixed. The problem is that if the transactions for "Other nei" countries are not updated, then the old values remain in the dataset. In this case, I think that the transactions were not updated (no values were generated) because there was just one partner (South Africa).

**Comment by baldwinkl** [comment] 2017-09-06 07:47
So this is a known problem with the functioning of the module, in that if the new transaction is "no transaction", then the old values stay in the working system. There must be a way to automatically clean these out of the dataset after each run...i.e. replace them with zero values? I'm just thinking of any solution that would not require wiping the whole dataset each time this problem occurs. Welcome your thoughts.

**Comment by chrmongeau** [comment] 2017-09-13 09:28
I had a conversation with Giorgio and he said that giving that this is a problem that occurs because we are "refining" the module (indeed, when this problem occurred it was because bugs in the code) the best solution is to ask for a dataset wiping each time we (you) find a problem. He also said that he is open to study some system solution for this kind of problems, but he said that it would be preferable to develop some code in the module itself to check which previous values are not generated in a given run of the code, set them to NA and then write back. I think that this would increase computation time, so for now it's not probably a very good idea and we should stick to the current set up.

**Comment by chrmongeau** [comment] 2017-10-27 14:43
This was fixed by 9e18829. See comments in #164.

**Closed as completed by chrmongeau** 2017-10-27 14:43 UTC
Labels: Type: Enhancement, management, Priority: Medium
